export const config = {
  MEMORY_ENABLED: process.env.MCPU_MEMORY_ENABLED === "true" || process.env.MCPU_MEMORY_ENABLED === undefined,
  MEMORY_DRIVER: process.env.MCPU_MEMORY_DRIVER || "sqlite",
  MEMORY_CONNECTION_URL: process.env.MCPU_MEMORY_CONNECTION_URL || "sqlite:///./mcpu-memory.db",
  
  SQL_READONLY_ENABLED: process.env.MCPU_SQL_READONLY_ENABLED !== "false",
  SQL_MAX_ROWS: Number(process.env.MCPU_SQL_MAX_ROWS || 500),
  SQL_TIMEOUT_MS: Number(process.env.MCPU_SQL_TIMEOUT_MS || 3000),

  BUFFER_DRAIN_ENABLED: process.env.MCPU_BUFFER_DRAIN_ENABLED !== "false",
  BUFFER_DRAIN_RATIO: Number(process.env.MCPU_BUFFER_DRAIN_RATIO || 0.75),
  BUFFER_DRAIN_MIN_INTERVAL_MS: Number(process.env.MCPU_BUFFER_DRAIN_MIN_INTERVAL_MS || 1000),
  BUFFER_DRAIN_WRITE_MODE: process.env.MCPU_BUFFER_DRAIN_WRITE_MODE || "batch",
  BUFFER_DRAIN_INSERT_DEDUP: process.env.MCPU_BUFFER_DRAIN_INSERT_DEDUP !== "false",

  RAW_OBSERVATION_ENABLED: process.env.MCPU_RAW_OBSERVATION_ENABLED !== "false",
  RAW_RETENTION_HOURS: Number(process.env.MCPU_RAW_RETENTION_HOURS || 24),

  SUMMARY_ENABLED: process.env.MCPU_SUMMARY_ENABLED !== "false",
  SUMMARY_WINDOW_MS: Number(process.env.MCPU_SUMMARY_WINDOW_MS || 60000),
  SUMMARY_RETENTION_DAYS: Number(process.env.MCPU_SUMMARY_RETENTION_DAYS || 365),

  TOOL_CALL_RETENTION_DAYS: Number(process.env.MCPU_TOOL_CALL_RETENTION_DAYS || 365),
  SIGNAL_EVENT_RETENTION_DAYS: Number(process.env.MCPU_SIGNAL_EVENT_RETENTION_DAYS || 365),
};
